version: "3.0"
services: 
    application:
        container_name: flask
        image: flask
        build:
            context: .
            dockerfile: .docker/flask.development.dockerfile
        ports:
            - "5000:5000"
        volumes: ['.:/var/www']
        env_file: .docker/env/app.production.env